name: Build job


jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
      - name: Clone Repository (Latest)
        uses: actions/checkout@v2
        with:
          repository: 'pavan3999-1/tachiyomi'
          fetch-depth: 0
        if: github.event.inputs.git-ref == ''
      - name: Clone Repository (Custom Ref)
        uses: actions/checkout@v2
        if: github.event.inputs.git-ref != ''
        with:
          repository: 'pavan3999-1/tachiyomi'
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 8.0.212
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.212
          java-package: jdk
          architecture: x64

      - name: Get previous release
        id: last_release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ github.token }}
          exclude_types: "draft|prerelease"
          view_top: 1

      - name: Set env variables
        run: |
          set -x

          commit_count=$(git rev-list --count HEAD)
          echo "COMMIT_COUNT=$commit_count" >> $GITHUB_ENV
          current_sha=$(git rev-parse --short HEAD)
          echo "CURRENT_SHA=$current_sha" >> $GITHUB_ENV

          prev_commit_count=$(echo "${{ steps.last_release.outputs.tag_name }}" | sed -e "s/^r//")
          commit_count_diff=$(expr $commit_count - $prev_commit_count)
          prev_release_sha=$(git rev-parse --short HEAD~$commit_count_diff)
          echo "PREV_RELEASE_SHA=$prev_release_sha" >> $GITHUB_ENV

          echo "COMMIT_LOGS<<{delimiter}
          $(curl -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/pavan3999-1/tachiyomi/compare/$prev_release_sha...$current_sha" \
            | jq '[.commits[]|{message:(.commit.message | split("\n")), username:.author.login}]' \
            | jq -r '.[]|"- \(.message | first) (@\(.username))"')
          {delimiter}" >> $GITHUB_ENV

      - name: Get NDK 
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;19.2.5345600"

      - name: Build Release APK
        run: bash ./gradlew assembleDevDebug --stacktrace

      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          # The directory to find your release to sign
          releaseDirectory: app/build/outputs/apk/dev/debug
          # The key used to sign your release in base64 encoded format
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          # The key alias
          alias: ${{ secrets.ALIAS }}
          # The password to the keystore
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          # The password for the key
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Clean up build artifacts
        run: |
          cp app/build/outputs/apk/dev/debug/app-dev-debug.apk tachiyomi-r${{ env.COMMIT_COUNT }}.apk
          md5=`md5sum tachiyomi-r${{ env.COMMIT_COUNT }}.apk | awk '{ print $1 }'`
          echo "APK_MD5=$md5" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: r${{ env.COMMIT_COUNT }}
          name: Tachiyomi Preview r${{ env.COMMIT_COUNT }}
          body: |
            Commits: https://github.com/pavan3999-1/tachiyomi/compare/${{ env.PREV_RELEASE_SHA }}...${{ env.CURRENT_SHA }}

            ${{ env.COMMIT_LOGS }}

            MD5: ${{ env.APK_MD5 }}
          files: |
            tachiyomi-r${{ env.COMMIT_COUNT }}.apk
          draft: ${{ github.event.inputs.dry-run != '' }}
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prune old releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          keep_latest: 10
          delete_tags: true

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '*.md'
      - '*.yml'
    branches: [ master ]
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.yml'
    branches: [ master ]
